# Generated by Django 5.2.4 on 2025-08-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_authpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('rt', models.CharField(max_length=3)),
                ('rw', models.CharField(max_length=3)),
                ('foto', models.ImageField(upload_to='warga/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
